dataset:
  country: Uganda
  source: WB
  level: cluster
  month: 1
  year: 2011
  filename: WB_Uganda_2011_cluster.csv
satellite:
  grid: F182013.v4c_web.stable_lights.avg_vis.tif
  source: Google
  step: 0
network:
  model: ResNet50
  layer: AvgPool
